create table if not exists public.newsletter_history (
    id bigint generated by default as identity primary key,
    source text not null,
    article_title text not null,
    article_link text not null,
    delivery_id text not null,
    sent_at timestamptz not null default now(),
    constraint newsletter_history_source_link_key unique (source, article_link)
);

alter table public.newsletter_history enable row level security;

alter table public.newsletter_history
add column if not exists delivery_id text;

update public.newsletter_history
set delivery_id = 'legacy-' || to_char(sent_at at time zone 'Asia/Seoul', 'YYYY-MM-DD')
where delivery_id is null;

alter table public.newsletter_history
alter column delivery_id set not null;

create index if not exists newsletter_history_sent_at_idx
on public.newsletter_history (sent_at desc);

create index if not exists newsletter_history_delivery_id_idx
on public.newsletter_history (delivery_id);
